language: python
#python --version
python: 3.7.7
#pip3 freeze > requirements.txt
install: pip install -r requirements.txt
#script: python gym_continuousDoubleAuction/test.py
# use > /dev/null to discard stdout from CDA env
script:
  - python gym_continuousDoubleAuction/test/test_OrderBook.py > /dev/null
  - python gym_continuousDoubleAuction/test/test_cda_nsp.py > /dev/null
