language: python
#python --version
python: 3.7.2
#pip3 freeze > requirements.txt
install: pip install -r requirements.txt
#script: python gym_continuousDoubleAuction/test.py
# use > /dev/null to discard stdout from CDA env
script: python gym_continuousDoubleAuction/test_CDA_env_disc_RLlib.py > /dev/null
